- .eslintignore
- .github/workflows/build-and-deploy.yml
- .prettierignore
After discovering that the action for uploading to Azure failed, I've used the time to reorganize the actions into separate jobs. Every action using a remote service (deployment, uploading of code-coverage report) now runs in a separate job which starts after the `test and build` job.
During validation, I also discovered that some commands (eslint and prettier) do not yet ignore the `coverage` folder, which contains an HTML report of the code-coverage of the project.
> Reorganized github actions (and ignore coverage folder) 

- .github/workflows/build-and-deploy.yml
This is the result of scanning the repository for IaC and CI/CD vulnerabilities with [checkov](https://checkov.io)
Testing out whether such a tool could make sense to add as a standard.
> Limit GitHub Actions token permissions

- src/App.vue
- src/api/client.ts
- src/api/playlists.ts
- src/components/PlaylistOverview.vue
- src/composables/useStore.ts
- src/router.ts
- src/store.ts
- src/vue.d.ts
I see you've been storing the token in addition to using the library, although the auth0 sdk handles this internally, so there's no reason to add additional logic. 
Here's an example of how you could avoid loading the application after auth0 has initialized.
The BMM API SDK should probably also handle the authentication flow internally (perhaps accept an async "token factory" on instantiating the client), so the requests are simplified. In src/api/client I have a proposed solution to simplify using the generated models from the sdk.
> Simplify authentication.

- .github/workflows/build-and-deploy.yml
It seems that codecov needs the code alongside with the coverage report. Previously those tasks were split because we saw the azure-upload failing, which shouldn't happen to codecov as the action doesn't get the task to fail if the upload fails (see https://github.com/codecov/codecov-action#arguments - fail_ci_if_error)
> Moved uploading of codecov files to main task

- package.json
- pnpm-lock.yaml
- vite.config.ts
As types (typescript) are not checked either, it would be weird to have them in but not typescript. The vite team has deliberately left it out and its better to remain consistent here (https://vitejs.dev/guide/features.html#transpile-only).
Another option, which is also provided on the vites website is to introduce type-checking on change. For me, the argument, that the code editor should take care of that is a perfectly valid argument, which also applies to all the eslint and stylelint rules as well. If they're not explicitly getting the code to fail, this is a better way.
For everyone who doesn't have a such rich editor, he is always free to use VSCode, for which this project has a preset for, or run the package-command `lint` once in a while. The commands there can also be each …
> Remove vite plugins for eslint and stylelint

- .eslintignore
- .prettierignore
- app.vue
- components/sidebar/SidebarElement.vue
- electron/main.ts
- electron/preload.ts
- nuxt.config.ts
- pages/[...error].vue
- plugins/3.mediaPlayer.ts
- plugins/updateRouterOnRouteChangeEvent.client.ts
Did quite some changes on handling links which sum up in that links from external sources (another application opens `bmm://` links) and external links (links to `bmm.brunstad.org` via `http` or `https`) are handled by vues router.
The message shown to the user in electron while the login is in progress could do well with some styling, but I'll for now leave it up to @sclausendk to define how it should look like.
I've also added a long awaited logout link - just for having one...
Fixes #123 and #128
> Handling of links and login in electron

- plugins/3.mediaPlayer.ts
- plugins/4.mediaKeys.ts
Fixes #136.
As far as I could test, registering the DOM Media Session already fixed all of our requests for handling media keys - at least on MacOS.
If needed, I'll later include the registering of the media-keys, but at least on MacOS none of them could be registered, and the DOM Media Session did the job quite well.
[electron-media-keys.patch](https://github.com/bcc-code/bmm-web/files/11892859/electron-media-keys.patch)
Because of some quirx in typescript, this PR includes #159, which should be merged first.
> Media keys

- .gitignore
- components/track/TrackList.vue
- pages/album/[id].vue
- pages/index.vue
[Typings for `ref()` can be inferred, and it's also correct to do so because those typings are not just `Ref<T>`, but `Ref<UnwrapRef<T>>`](https://vuejs.org/api/reactivity-core.html#ref), which we could import from `vue`; but it's even better to have types inferred.
> Infer typing ref

- plugins/1.auth0.client.ts
To solve #153
I haven't managed to test this properly yet. I tried to connect this to my own Auth0 client, to set a shorter access token time-out. That didn't work well, because that access token doesn't grant access to BMM. So you get access denied anyway.
So now I hope this PR‌ will make a build, and I can install that locally. Then I'll use that that build for a few days, to see whether it works.
> Refresh access token

- components/TimeDuration.vue
The rendering of the duration on some devices was odd (getting 60 for seconds, and more complex errors like the 10th of seconds not updating properly...) but also the minutes were a rounded value, which reported 1 for 0,6 minutes.
> Fix time duration

- .eslintrc.json
The primary purpose of `no-param-reassign` is to guard the behaviour of `arguments`[^1]. Apparently one of our defaults has additionally enabled the sub-rule for argument property reassignment. I don't think it's a good fit for a Vue + Nuxt project as those APIs make it necessary in some methods. E.g. `defineNuxtPlugin` may have to modify properties of the input `nuxtApp`.
[^1]: https://eslint.org/docs/latest/rules/no-param-reassign
> Disable `no-param-reassign` for properties.

- app.vue
- locales/en.json
Errors by the login module (like about a expiry token missing, introduced by #204), were not reported to the user but silently hidden.
This change will show the login error to the user, will give him the option to log out and try again (which is what helps for #204) or contact the support (mail address taken from the profile-menu).
> Show error of login module

- components/track/TrackItem.vue
Since #221, we've had the problem that a users action on a dropdown item of a track seems to be ignored. Actually, it is executed, but most of them are overwritten by the click-action of the track itself.
This PR will stop the propagation of a click action beyond the dropdown.
> Stop click-propagation of any item in track dropdown

- components/ChangeLocale.vue
- components/ProfileMenu.vue
- components/dialog/DialogBase.vue
- locales/en.json
- package.json
- pnpm-lock.yaml
Using the HeadlessUI Dialog as a base gives us better accessibility out of the box, with keyboard navigation, close on escape, better screen reader support etc.
> [Dialog] Use HeadlessUI Dialog component as base of `DialogBase` component

- components/MediaPlayer.vue
- components/TextMarquee.vue
- modules/figma2tailwind/convertToTailwind.ts
Added a component for content in marquee, but also changed the marquee-effect to be linear, but first start after 2 seconds. Furthermore, the effect will start over again if a new text appears, which also is too long.
The space between the repeated text is `pr-14`, which is added in the `marquee` component if the variable `contentIsTooLarge` is true.
The mini-player does not have the text as marquee (as discussed @kkuepper), but the full-size player has it both for the title and the second line.
The speed is not a fixed amount of seconds, but the `marquee` component has a speed defined in pixel per second.
I also found it quite annoying if a text, which just didn't quite wrap by very few pixel (not noticeable) also was rotating, which is why I added `bufferSpace`. I just have an example …
> Better marquee

- plugins/4.mediaPlayer.ts
- plugins/mediaPlayer/mediaPlayer.spec.ts
- plugins/mediaPlayer/mediaPlayer.ts
**Problem**
Right now if you leave the tab open until the access token expires, it's not going to refresh the token and playback won't start.
**Cause**
The mediaplayer had an unecessary cache for the token. It's not being refreshed upon expiry because we are watching "isAuthenticated".
**Solution**
The auth0 sdk has an internal cache, so we can use getAccessTokenSilently() directly.
This also mirrors how it's done everywhere else, e.g. https://github.com/bcc-code/bmm-web/blob/0cb1e1d9915236d1e0d66c943015abc253aa2081/components/ProtectedImage.vue#L16
> fix: media player auth token was not being refreshed

- plugins/4.mediaPlayer.ts
- plugins/mediaPlayer/MediaTrack.spec.ts
- plugins/mediaPlayer/MediaTrack.ts
- plugins/mediaPlayer/mediaPlayer.spec.ts
- plugins/mediaPlayer/mediaPlayer.ts
In PR #341 a mechanism was introduced which refetches the access-token before the start of every track (if not cached - see [`getAccessTokenSilently()`](https://auth0.github.io/auth0-vue/interfaces/GetTokenSilentlyOptions.html)).
Since `getAccessTokenSilently()` returns a promise, this would delay the instantiation of the `MediaTrack` item, means, the media player will show something old, as the new track has not been set yet. Neither are errors handled.
I've refactored the `MediaTrack` class to allow for a delayed setting of the source and some error handling if the token cannot be fetched. ~Currently, we report the song as ended, which would skip the song and continue to the next, which might fail again and thus continue to the end of the list.~ IMO, this is at least better than not …
> Don't pospone track initialization

- components/AlbumDetails.vue
- components/ButtonStyled.vue
- components/DocumentList.vue
- components/EndlessDocumentList.vue
- components/GenericListItem.vue
- components/PrivatePlaylistMenu.vue
- components/ProfileMenu.vue
- components/RecommendationItem.vue
- components/album/SubAlbum.vue
- components/track/TrackChangeLocale.vue
- components/track/TrackMenu.vue
- pages/playlist/contributor/[id]/index.vue
- pages/playlist/curated/[id]/index.vue
- pages/playlist/podcast/[id]/index.vue
- pages/search/[[term]].vue
- pages/track/[id]/[...language].vue
- pages/track/[id]/index.vue
Just some things I saw could do good of some improvements in the last PRs.
Why I implemented [Dynamic width for context menu](https://github.com/bcc-code/bmm-web/commit/154599d5253011f9aeb0c3869ec07d46339cf372) is best explained in these two screenshots:
**Before:**
**After:**
> Small adjustments

- modules/figma2tailwind/index.ts
- modules/icons/generator/index.ts
We are planning to move to [emitting absolute paths in `builder:watch` in Nuxt v4](https://github.com/nuxt/nuxt/issues/25339). You can see a little more about the history in the PR linked in that issue.
This PR is an attempt to use a forward/backward compatible approach, namely resolving the path to ensure it's absolute, then making it relative so your existing code will continue to work.
This should be safe to merge as is, but do let me know if you have any concerns about this approach.
> fix: adopt forward-compatible approach to `builder:watch`

- plugins/4.mediaPlayer.ts
- plugins/mediaPlayer/MediaTrack.ts
Fixes #328.
I've also added error reporting for thrown elements on `play()`. All of them (excepted for `NotAllowedError`) are reported. @kkuepper please let me know if you want them reported as well. Those are the errors you faced in #328.
> Pause autoplay on error

- components/track/TrackMenu.vue
- composables/user.ts
Normally useAsyncData with a key and dedupe is enough, as it's cached, but since this is only used 1 place in the app, the cache clears whenever all "listening" scopes have unmounted. So we need to cache the thing.
Feels like it should be simpler than this but I couldn't think of anything if one wants to use useAsyncData (it's handy as it gives you loading states etc ootb).
> fix: cache currentuser composable

- components/AppToolbar.vue
reproduction steps:
- open Electron app (tested on M1 Mac)
- open a playlist
- -> no back button appearing
- hit Cmd + R (which refreshes the website)
- -> back button is now there
> fix back button not working on 1st load in Electron

- components/media-player/MediaPlayerOpen.vue
- plugins/mediaPlayer/Queue.spec.ts
- plugins/mediaPlayer/Queue.ts
- plugins/mediaPlayer/mediaPlayer.ts
Fixes #189 (?)
I used the [vue-draggable-plus](https://github.com/Alfred-Skyblue/vue-draggable-plus), as [vue-draggable-next](https://github.com/SortableJS/vue.draggable.next) doesn't have great TypeScript support, and seems not actively maintained.
https://github.com/bcc-code/bmm-web/assets/18753964/d8e72a9e-fa4d-4734-8a7b-07b907723106
> Queue: Add reorder functionality

- components/DocumentList.vue
- components/EndlessDocumentList.vue
- components/TileItem.vue
- components/media-player/MediaPlayerOpen.vue
- components/track/TrackItem.vue
- components/track/TrackList.vue
- components/track/TrackMenu.vue
- pages/index.vue
- pages/playlist/contributor/[id]/index.vue
- pages/playlist/curated/[id]/index.vue
- pages/search/[[term]].vue
- plugins/4.mediaPlayer.ts
- plugins/mediaPlayer/EnrichedTrackModel.ts
- plugins/mediaPlayer/Queue.spec.ts
- plugins/mediaPlayer/Queue.ts
- plugins/mediaPlayer/mediaPlayer.spec.ts
- plugins/mediaPlayer/mediaPlayer.ts
So far this information has mainly been used for Analytics purposes. But we also use it to determine which are "Your top playlists" and we're getting reports about people listening to Daily Mix a lot, but not seeing it in their top playlists.
This PR creates the necessary infrastructure and sets the correct values for 3 of the 19 views. The other views can be added at a later time.
> provide playbackOrigin for CuratedPlaylist, Contributor and Tile

- components/media-player/MediaPlayer.vue
- layouts/default.vue
- tailwind.config.ts
This is how it currently looks:
https://github.com/user-attachments/assets/6d73bc75-a968-46c2-8355-7bbeffc4fe96
With the transition it looks like this:
https://github.com/user-attachments/assets/b58471eb-ab9b-4aa2-8819-a469bd77a101
> feat(player): smoothly animate player width when toggling open state

- components/EndlessDocumentList.vue
- components/track/TrackItemSkeleton.vue
- components/track/TrackList.vue
Adds slightly better looking skeleton loaders. They now look a bit more like real tracks.
Old
New
With thumbnails
> feat: improved skeleton loaders

- pages/dashboards/fra-kaare.vue
A couple of fixes for some issues I found.
- The "change" column wasn't visible for the "small churches" table
- Set a fixed number of decimals for the change column
> fix(dashboard): small fixes for the fra kaare dashboard

- components/TextMarquee.vue
- components/media-player/MediaPlayerOpen.vue
This is how it currently looks:
https://github.com/user-attachments/assets/c853ccd4-9575-4c0d-90ba-4d29f9793529
This is after the change:
https://github.com/user-attachments/assets/ce77a724-885b-4f5a-86b6-0c25b62bddfe
> feat(player): make marquee text fade out at the edges

- .vscode/extensions.json
All its functionality has been replaced by `vue.volar`, which is already on the recommendations list anyway.
> Remove deprecated extension:

- plugins/mediaPlayer/Queue.ts
Previous algorithm had several issues. See #219 for the details.
New algorithm:
- Retains desired non-shuffle behaviour. The current track is kept at the top.
- Proper randomisation only dependent on the randomness of `Math.random()`, not on the pre-shuffle order of the track list.
- Proper stable comparison, the result of comparing two tracks A and B is the same at any point during the shuffle process.
I chose the Schwartzian Transform sort as basis for the shuffle algorithm. It is fairly easy to understand _why_ this algorithm is only dependent on the source of randomness. Compared to the BMM app's Fisher-Yates, which requires more mathematical proof that it is so, or the old implementation which required more mathematical proof that it is _not_ so.
> Replace shuffle algorithm

- components/ItemCard.vue
This PR introduces a quick way to see the titles of each playlist / album / podcast.
I just put the title beneath the cover for now, as we don't have any design spec yet, as discussed in #451 
This does make the screen more "noisy", but that is an ok tradeoff in my opinion.
> feat: add title beneath cover in album cards

- components/media-player/MediaPlayer.vue
- components/media-player/MediaPlayerClosed.vue
- components/media-player/MediaPlayerOpen.vue
Adds a simple transition for the track cover in the media player using the [View Transition API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API) to visually connect the two states.
If a browser doesn't support it, it will simply work as before.
https://github.com/user-attachments/assets/56d225f3-e91b-4b35-8aed-286e874b1e0b
https://github.com/user-attachments/assets/bf8421c7-16f2-4234-836e-ce89336ca451
> [Media Player] Transition cover between open and closed states

- locales/da.json
- locales/de.json
- locales/pt.json
- locales/ro.json
> New Phrase Updates
