package.json
pnpm-lock.yaml
src/App.vue
src/main.ts
src/router.ts
src/views/About.vue
src/views/Contact.vue
src/views/Home.vue
tsconfig.json
vite.config.ts

Added vue-router and relative imports. Relative imports are preferable because you won't have to change imports when moving files around.

Add routing

---

.eslintrc.json
.vscode/settings.json
src/store.ts
tsconfig.node.json

@u12206050 I've here a.o. interfered with some of the things you did lately, also reverted your choice of formatter - see the commit message for details.

Stricter typescript checks

---

package.json
pnpm-lock.yaml
src/components/PlaylistOverview.vue
src/router.ts
src/views/CuratedPlaylistDetails.vue

- allows clicking on playlist on home
- lists content (tracks) of a playlist

add playlist details view

---

src/components/PlaylistOverview.vue
src/components/ProtectedImage.spec.ts
src/components/ProtectedImage.vue

Implement a wrapper for images that need a token.

Implement wrapper for images 

---

src/components/PlaylistOverview.spec.ts
src/components/ProtectedImage.spec.ts
src/components/ProtectedImage.vue
src/views/Playlist/CuratedPlaylistDetails.vue
src/views/Playlist/PrivatePlaylist.vue

Fail switching playlist routes

---

app.vue
components/MediaPlayer.vue
components/sidebar/SidebarElement.vue
components/sidebar/SidebarGroup.vue
layouts/default.vue
pages/playlist/curated/[id].vue

App layout: Made the sidebar scroll independent from the content area

---

app.vue
components/AppToolbar.vue
components/ContentSection.vue
components/DropdownMenu.vue
components/ErrorMsg.vue
components/MediaPlayer.vue
components/album/SubAlbum.vue
components/playlist/PlaylistCard.vue
components/playlist/PlaylistCarousel.vue
components/sidebar/SidebarElement.vue
components/sidebar/SidebarGroup.vue
components/sidebar/SidebarItem.vue
components/track/TrackItem.vue
components/track/TrackList.vue
layouts/default.vue
package.json
pages/album/[id].vue
pages/index.vue
pages/playlist/curated/[id].vue
pages/playlist/private/[id].vue
pnpm-lock.yaml
prettier.config.js

Since styles are used all-over and I don't want a heavy merge-conflict on everything, it's best to merge this after all other PRs currently open here are merged.
Please rebase on master (or merge master into this) and run `npx prettier . --write` as last commit here which will update all files according to the new prettier rules.

Added and configured tailwind for prettier

---

electron/main.ts

Fixes #124 and closes a gap between dev and prod. Both now use the custom protocol for reaching out for internal data.

Electron - login in browser

---

nuxt.config.ts

This was annoying me for quite a while already ... Finally fixed 🎉

Stop changing the app-language when routing

---

README.md
electron/main.ts

Tested on MacOS (Intel) and Windows

Windows deep links

---

.github/workflows/electron.yml
README.md
electron-builder.yml
package.json

Copy of PR #150 - this time in this repo, which allows the usage of secure variables.

Appimage package improvements (merged)

---

.github/workflows/electron.yml
README.md
electron-builder.yml
package.json

Minor improvements improve how the produced AppImage integrates with most XDG compatible desktops.
Didn't manage to fully fix URI handling, but @SimonSimCity's branch has pretty much the same code that I wrote, so I threw mine out.

Appimage package improvements

---

components/contributor/ContributorListItem.vue
composables/contributor.ts
pages/index.vue
pages/playlist/contributor/[id]/index.vue

Fixes #133.
The commits should be reviewed separately. Specially the last two changes basically changed almost every line of the home-page because of white-spacing ... You can also reduce the amount of clutter by disabling white-spaces for the diff.

Contributor playlist view

---

components/DropdownMenu.vue
components/MediaPlayer.vue
components/ProfileMenu.vue
components/album/SubAlbum.vue
components/track/TrackItem.vue
pages/playlist/curated/[id]/index.vue

Make use of [event-modifiers](https://vuejs.org/guide/essentials/event-handling.html#event-modifiers) instead of writing it out in code.

Event modifier

---

nuxt.config.ts
pages/index.vue
plugins/2.applicationInsights.ts

Fixing some issues which prevented me from logging in.

Electron fix startup

---

layouts/default.vue

... if the size of the viewport exceeds all content

Fix navigation sidebar not filling full height

---

pages/search.vue

Building the search view so that it matchs with the design

search box view

---

components/sidebar/AddPlaylist.vue
components/sidebar/SidebarElement.vue
composables/privatePlaylists.ts
locales/en.json

@sclausendk there was no design of how this should look like, so I created one my own which to me doesn't look all to bad 😎 Would be nice to get your feedback on this. The icons are just stolen from somewhere I found fitting ...

Feature: Create private playlist

---

.github/workflows/electron.yml
.gitignore
electron-builder.yml
electron/main.ts

Previously the app was a lot a bigger since it contained itself & the node_modules folder.

smaller app

---

components/album/AlbumItem.vue
components/playlist/PlaylistItem.vue
components/podcast/PodcastItem.vue
composables/search.ts
pages/search.vue

@SimonSimCity Please just for the second PR before investgate.

Adding Album in results of Search Input

---

components/track/TrackDetails.vue
locales/de.json
locales/en.json

should solve second subtask of https://github.com/bcc-code/bmm-web/issues/239 but there is an open question about "Reference" and "hör sangen her" link.

added missing track detail information

---

crowdin.yml
i18n.config.ts
locales/af.json
locales/bg.json
locales/cs.json
locales/da.json
locales/el.json
locales/es.json
locales/et.json
locales/fi.json
locales/fr.json
locales/he.json
locales/hr.json
locales/hu.json
locales/it.json
locales/pl.json
locales/pt.json
locales/ro.json
locales/ru.json
locales/sl.json
locales/tr.json
locales/uk.json
locales/zh.json

When users start using the project, not all languages will be translated.
Therefore I removed the languages where we don't have any translations yet. Norwegian is only 31% translated, but I'm willing to commit that we will find someone to translate before the project goes live.
Once we're live, we will ask translators if they are willing to translate and add additional languages as soon as they are 100% translated.

delete untranslated languages

---

components/album/AlbumItem.vue
components/contributor/ContributorListItem.vue
components/playlist/PlaylistItem.vue
components/podcast/PodcastItem.vue
components/track/TrackItem.vue
components/track/TrackList.vue
modules/figma2tailwind/convertToTailwind.ts
pages/index.vue
pages/search.vue

Fix #263.
@BeastiW Extending `tailwind.conf.ts` looks good to me as of now. We do not yet have a common approach for doing it otherwise. It's hacky, but fills the need for now.
The mouseover and other things should be fixed. Would like to have your feedback on the changes I've done. Please compare the PR also against the current design in terms of spacing etc - I haven't taken too much care about this. would be nice if you could do it.

263 align track item design

---

electron/main.ts
package.json
pnpm-lock.yaml

this uses ElectronStore to persist the window bounds in a json file and restore them at next app open.
@steffanhalv Would be nice to profit from your experience if that's enough or if other platforms need additional code. It seems to work fine on my M1 Mac when adding or removing monitors.

persist and restore window position

---

components/AppToolbar.vue

Resolving https://github.com/bcc-code/bmm-web/pull/271#discussion_r1472667007
Has to be tested in Electron.

Show back-button if browser can go back

---

components/MediaPlayer.vue
components/track/TrackContributors.vue
components/track/TrackMenu.vue

Add navigation for going to contributors profile

---

composables/podcast.ts
pages/playlist/podcast/[id]/index.vue

:sparkles: implement play/shuffle functionality for podcasts

---

assets/icons/playing (animation).css
components/MediaPlayer.vue

Updated the morphing of the playing animation and linked the playing-state to the paused-state of the player.

Better playing animation

---

app.vue
components/ButtonStyled.vue
components/DocumentList.vue
components/contributor/ContributorListItem.vue
components/track/TrackItem.vue
composables/contributor.ts
composables/podcast.ts
locales/en.json
pages/playlist/contributor/[id]/index.vue
pages/playlist/curated/[id]/index.vue
pages/playlist/podcast/[id]/index.vue
pages/playlist/private/[id]/index.vue
plugins/mediaPlayer/mediaPlayer.ts

this PR contains:
- add (working) actions on tracks
- streamline styling of track collections
- use circular image for contributors
- smaller adjustments

track collections

---

components/MediaPlayer.vue
composables/defineShortcuts.ts
composables/useShortcuts.ts
package.json
pnpm-lock.yaml

implement keyboard shortcuts

---

.github/workflows/electron.yml

Bible Explorers are also building an app and we want to share some of the secrets

change secrets to organization secrets

---

components/MediaPlayer.vue
plugins/mediaPlayer/Queue.ts
plugins/mediaPlayer/mediaPlayer.spec.ts
plugins/mediaPlayer/mediaPlayer.ts

... and added some tests and refactored the changes of #319.
Please read the commit notes for further details.

Added the track-repeat mode

---

.eslintrc.json

A warning is not to say that things have to be corrected, they just show a potential for error. Likewise, all of these warnings, added here, show a potential for error. When being cautious, it doesn't harm, but when being unaware of the danger, we might bring ourselves in situations where our project might not deliver the expected result.

Add I18n warnings for irregular things

---

components/sidebar/SidebarElement.vue

https://github.com/bcc-code/bmm-web/assets/18753964/a6a8f67c-7df7-4ee1-83b8-936876772fb5

Make mobile sidebar animated

---

tailwind.config.ts

With `auto-fit`:
https://github.com/bcc-code/bmm-web/assets/18753964/5f81aeff-c6ae-4d6c-a5f3-853c55cc2f1e
With `auto-fill`:
https://github.com/bcc-code/bmm-web/assets/18753964/4998f128-94c9-423a-8945-6312b53eac5e

fix(cover-list): replace auto-fit with auto-fill

---

electron/main.ts
electron_builder.js

The icons were not included in the build so therefore the thumbnail preview was missing the assets.

Fix thumbnail buttons

---

components/ProfileMenu.vue
components/dropdown/DropdownMenu.vue
components/dropdown/DropdownMenuItem.vue

Profile menu: display signed-in user's information

---

app.vue
locales/en.json
pages/[...error].vue
pages/album/[id].vue
pages/archive/[year].vue
pages/archive/index.vue
pages/audiobooks.vue
pages/browse/audiobooks.vue
pages/browse/events.vue
pages/browse/index.vue
pages/contributors.vue
pages/copyright.vue
pages/download.vue
pages/index.vue
pages/music.vue
pages/playlist/contributor/[id]/index.vue
pages/playlist/curated/[id]/index.vue
pages/playlist/podcast/[id]/index.vue
pages/playlist/private/[id]/index.vue
pages/playlist/shared/[sharingsecret].vue
pages/search/[[term]].vue
pages/speeches.vue
stores/toolbarTitle.ts
utils/setTitle.ts
utils/setTitleOfDocumentList.ts

Page title

---

.github/workflows/build-and-deploy.yml
nuxt.config.ts
package.json
plugins/00.sentry.client.ts
pnpm-lock.yaml

We are migrating to Sentry for error and crash reporting.

feat: add sentry integration

---

pages/lyrics/[id].vue
pages/lyrics/index.vue

Based on some feedback from Priscilla

chore(lyrics): make long copyright emptiable

---

components/sidebar/SidebarElement.vue

remove beta badge & hide version number on web

---

components/sidebar/SidebarElement.vue

feat: use favorites icon in sidebar

---

components/streak/StreakItem.vue
locales/en.json

feat: show time left to get streak in details dialog

---

locales/de.json
locales/et.json

New Phrase Updates

---

components/sidebar/SidebarElement.vue
locales/en.json

feat: move admin tools to its own sidebar group
